export interface CountryType {
  code: string;
  label: string;
  phone: string;
  suggested?: boolean;
}

export const default_map_pos: { lng: number, lat: number } = { lat: 46.58911069010469, lng: 7.565392374224711 };

export const countries: CountryType[] = [
  { code: 'AD', label: 'Andorra', phone: '376' },
  { code: 'AE', label: 'United Arab Emirates', phone: '971' },
  { code: 'AF', label: 'Afghanistan', phone: '93' },
  { code: 'AG', label: 'Antigua and Barbuda', phone: '1-268' },
  { code: 'AI', label: 'Anguilla', phone: '1-264' },
  { code: 'AL', label: 'Albania', phone: '355' },
  { code: 'AM', label: 'Armenia', phone: '374' },
  { code: 'AO', label: 'Angola', phone: '244' },
  { code: 'AQ', label: 'Antarctica', phone: '672' },
  { code: 'AR', label: 'Argentina', phone: '54' },
  { code: 'AS', label: 'American Samoa', phone: '1-684' },
  { code: 'AT', label: 'Austria', phone: '43' },
  { code: 'AU', label: 'Australia', phone: '61', suggested: true },
  { code: 'AW', label: 'Aruba', phone: '297' },
  { code: 'AX', label: 'Alland Islands', phone: '358' },
  { code: 'AZ', label: 'Azerbaijan', phone: '994' },
  { code: 'BA', label: 'Bosnia and Herzegovina', phone: '387' },
  { code: 'BB', label: 'Barbados', phone: '1-246' },
  { code: 'BD', label: 'Bangladesh', phone: '880' },
  { code: 'BE', label: 'Belgium', phone: '32' },
  { code: 'BF', label: 'Burkina Faso', phone: '226' },
  { code: 'BG', label: 'Bulgaria', phone: '359' },
  { code: 'BH', label: 'Bahrain', phone: '973' },
  { code: 'BI', label: 'Burundi', phone: '257' },
  { code: 'BJ', label: 'Benin', phone: '229' },
  { code: 'BL', label: 'Saint Barthelemy', phone: '590' },
  { code: 'BM', label: 'Bermuda', phone: '1-441' },
  { code: 'BN', label: 'Brunei Darussalam', phone: '673' },
  { code: 'BO', label: 'Bolivia', phone: '591' },
  { code: 'BR', label: 'Brazil', phone: '55' },
  { code: 'BS', label: 'Bahamas', phone: '1-242' },
  { code: 'BT', label: 'Bhutan', phone: '975' },
  { code: 'BV', label: 'Bouvet Island', phone: '47' },
  { code: 'BW', label: 'Botswana', phone: '267' },
  { code: 'BY', label: 'Belarus', phone: '375' },
  { code: 'BZ', label: 'Belize', phone: '501' },
  { code: 'CA', label: 'Canada', phone: '1', suggested: true },
  { code: 'CC', label: 'Cocos (Keeling) Islands', phone: '61' },
  { code: 'CD', label: 'Congo, Democratic Republic of the', phone: '243' },
  { code: 'CF', label: 'Central African Republic', phone: '236' },
  { code: 'CG', label: 'Congo, Republic of the', phone: '242' },
  { code: 'CH', label: 'Switzerland', phone: '41' },
  { code: 'CI', label: "Cote d'Ivoire", phone: '225' },
  { code: 'CK', label: 'Cook Islands', phone: '682' },
  { code: 'CL', label: 'Chile', phone: '56' },
  { code: 'CM', label: 'Cameroon', phone: '237' },
  { code: 'CN', label: 'China', phone: '86' },
  { code: 'CO', label: 'Colombia', phone: '57' },
  { code: 'CR', label: 'Costa Rica', phone: '506' },
  { code: 'CU', label: 'Cuba', phone: '53' },
  { code: 'CV', label: 'Cape Verde', phone: '238' },
  { code: 'CW', label: 'Curacao', phone: '599' },
  { code: 'CX', label: 'Christmas Island', phone: '61' },
  { code: 'CY', label: 'Cyprus', phone: '357' },
  { code: 'CZ', label: 'Czech Republic', phone: '420' },
  { code: 'DE', label: 'Germany', phone: '49', suggested: true },
  { code: 'DJ', label: 'Djibouti', phone: '253' },
  { code: 'DK', label: 'Denmark', phone: '45' },
  { code: 'DM', label: 'Dominica', phone: '1-767' },
  { code: 'DO', label: 'Dominican Republic', phone: '1-809' },
  { code: 'DZ', label: 'Algeria', phone: '213' },
  { code: 'EC', label: 'Ecuador', phone: '593' },
  { code: 'EE', label: 'Estonia', phone: '372' },
  { code: 'EG', label: 'Egypt', phone: '20' },
  { code: 'EH', label: 'Western Sahara', phone: '212' },
  { code: 'ER', label: 'Eritrea', phone: '291' },
  { code: 'ES', label: 'Spain', phone: '34' },
  { code: 'ET', label: 'Ethiopia', phone: '251' },
  { code: 'FI', label: 'Finland', phone: '358' },
  { code: 'FJ', label: 'Fiji', phone: '679' },
  { code: 'FK', label: 'Falkland Islands (Malvinas)', phone: '500' },
  { code: 'FM', label: 'Micronesia, Federated States of', phone: '691' },
  { code: 'FO', label: 'Faroe Islands', phone: '298' },
  { code: 'FR', label: 'France', phone: '33', suggested: true },
  { code: 'GA', label: 'Gabon', phone: '241' },
  { code: 'GB', label: 'United Kingdom', phone: '44' },
  { code: 'GD', label: 'Grenada', phone: '1-473' },
  { code: 'GE', label: 'Georgia', phone: '995' },
  { code: 'GF', label: 'French Guiana', phone: '594' },
  { code: 'GG', label: 'Guernsey', phone: '44' },
  { code: 'GH', label: 'Ghana', phone: '233' },
  { code: 'GI', label: 'Gibraltar', phone: '350' },
  { code: 'GL', label: 'Greenland', phone: '299' },
  { code: 'GM', label: 'Gambia', phone: '220' },
  { code: 'GN', label: 'Guinea', phone: '224' },
  { code: 'GP', label: 'Guadeloupe', phone: '590' },
  { code: 'GQ', label: 'Equatorial Guinea', phone: '240' },
  { code: 'GR', label: 'Greece', phone: '30' },
  { code: 'GS', label: 'South Georgia and the South Sandwich Islands', phone: '500' },
  { code: 'GT', label: 'Guatemala', phone: '502' },
  { code: 'GU', label: 'Guam', phone: '1-671' },
  { code: 'GW', label: 'Guinea-Bissau', phone: '245' },
  { code: 'GY', label: 'Guyana', phone: '592' },
  { code: 'HK', label: 'Hong Kong', phone: '852' },
  { code: 'HM', label: 'Heard Island and McDonald Islands', phone: '672' },
  { code: 'HN', label: 'Honduras', phone: '504' },
  { code: 'HR', label: 'Croatia', phone: '385' },
  { code: 'HT', label: 'Haiti', phone: '509' },
  { code: 'HU', label: 'Hungary', phone: '36' },
  { code: 'ID', label: 'Indonesia', phone: '62' },
  { code: 'IE', label: 'Ireland', phone: '353' },
  { code: 'IL', label: 'Israel', phone: '972' },
  { code: 'IM', label: 'Isle of Man', phone: '44' },
  { code: 'IN', label: 'India', phone: '91' },
  { code: 'IO', label: 'British Indian Ocean Territory', phone: '246' },
  { code: 'IQ', label: 'Iraq', phone: '964' },
  { code: 'IR', label: 'Iran, Islamic Republic of', phone: '98' },
  { code: 'IS', label: 'Iceland', phone: '354' },
  { code: 'IT', label: 'Italy', phone: '39' },
  { code: 'JE', label: 'Jersey', phone: '44' },
  { code: 'JM', label: 'Jamaica', phone: '1-876' },
  { code: 'JO', label: 'Jordan', phone: '962' },
  { code: 'JP', label: 'Japan', phone: '81', suggested: true },
  { code: 'KE', label: 'Kenya', phone: '254' },
  { code: 'KG', label: 'Kyrgyzstan', phone: '996' },
  { code: 'KH', label: 'Cambodia', phone: '855' },
  { code: 'KI', label: 'Kiribati', phone: '686' },
  { code: 'KM', label: 'Comoros', phone: '269' },
  { code: 'KN', label: 'Saint Kitts and Nevis', phone: '1-869' },
  { code: 'KP', label: "Korea, Democratic People's Republic of", phone: '850' },
  { code: 'KR', label: 'Korea, Republic of', phone: '82' },
  { code: 'KW', label: 'Kuwait', phone: '965' },
  { code: 'KY', label: 'Cayman Islands', phone: '1-345' },
  { code: 'KZ', label: 'Kazakhstan', phone: '7' },
  { code: 'LA', label: "Lao People's Democratic Republic", phone: '856' },
  { code: 'LB', label: 'Lebanon', phone: '961' },
  { code: 'LC', label: 'Saint Lucia', phone: '1-758' },
  { code: 'LI', label: 'Liechtenstein', phone: '423' },
  { code: 'LK', label: 'Sri Lanka', phone: '94' },
  { code: 'LR', label: 'Liberia', phone: '231' },
  { code: 'LS', label: 'Lesotho', phone: '266' },
  { code: 'LT', label: 'Lithuania', phone: '370' },
  { code: 'LU', label: 'Luxembourg', phone: '352' },
  { code: 'LV', label: 'Latvia', phone: '371' },
  { code: 'LY', label: 'Libya', phone: '218' },
  { code: 'MA', label: 'Morocco', phone: '212' },
  { code: 'MC', label: 'Monaco', phone: '377' },
  { code: 'MD', label: 'Moldova, Republic of', phone: '373' },
  { code: 'ME', label: 'Montenegro', phone: '382' },
  { code: 'MF', label: 'Saint Martin (French part)', phone: '590' },
  { code: 'MG', label: 'Madagascar', phone: '261' },
  { code: 'MH', label: 'Marshall Islands', phone: '692' },
  { code: 'MK', label: 'Macedonia, the Former Yugoslav Republic of', phone: '389' },
  { code: 'ML', label: 'Mali', phone: '223' },
  { code: 'MM', label: 'Myanmar', phone: '95' },
  { code: 'MN', label: 'Mongolia', phone: '976' },
  { code: 'MO', label: 'Macao', phone: '853' },
  { code: 'MP', label: 'Northern Mariana Islands', phone: '1-670' },
  { code: 'MQ', label: 'Martinique', phone: '596' },
  { code: 'MR', label: 'Mauritania', phone: '222' },
  { code: 'MS', label: 'Montserrat', phone: '1-664' },
  { code: 'MT', label: 'Malta', phone: '356' },
  { code: 'MU', label: 'Mauritius', phone: '230' },
  { code: 'MV', label: 'Maldives', phone: '960' },
  { code: 'MW', label: 'Malawi', phone: '265' },
  { code: 'MX', label: 'Mexico', phone: '52' },
  { code: 'MY', label: 'Malaysia', phone: '60' },
  { code: 'MZ', label: 'Mozambique', phone: '258' },
  { code: 'NA', label: 'Namibia', phone: '264' },
  { code: 'NC', label: 'New Caledonia', phone: '687' },
  { code: 'NE', label: 'Niger', phone: '227' },
  { code: 'NF', label: 'Norfolk Island', phone: '672' },
  { code: 'NG', label: 'Nigeria', phone: '234' },
  { code: 'NI', label: 'Nicaragua', phone: '505' },
  { code: 'NL', label: 'Netherlands', phone: '31' },
  { code: 'NO', label: 'Norway', phone: '47' },
  { code: 'NP', label: 'Nepal', phone: '977' },
  { code: 'NR', label: 'Nauru', phone: '674' },
  { code: 'NU', label: 'Niue', phone: '683' },
  { code: 'NZ', label: 'New Zealand', phone: '64' },
  { code: 'OM', label: 'Oman', phone: '968' },
  { code: 'PA', label: 'Panama', phone: '507' },
  { code: 'PE', label: 'Peru', phone: '51' },
  { code: 'PF', label: 'French Polynesia', phone: '689' },
  { code: 'PG', label: 'Papua New Guinea', phone: '675' },
  { code: 'PH', label: 'Philippines', phone: '63' },
  { code: 'PK', label: 'Pakistan', phone: '92' },
  { code: 'PL', label: 'Poland', phone: '48' },
  { code: 'PM', label: 'Saint Pierre and Miquelon', phone: '508' },
  { code: 'PN', label: 'Pitcairn', phone: '870' },
  { code: 'PR', label: 'Puerto Rico', phone: '1' },
  { code: 'PS', label: 'Palestine, State of', phone: '970' },
  { code: 'PT', label: 'Portugal', phone: '351' },
  { code: 'PW', label: 'Palau', phone: '680' },
  { code: 'PY', label: 'Paraguay', phone: '595' },
  { code: 'QA', label: 'Qatar', phone: '974' },
  { code: 'RE', label: 'Reunion', phone: '262' },
  { code: 'RO', label: 'Romania', phone: '40' },
  { code: 'RS', label: 'Serbia', phone: '381' },
  { code: 'RU', label: 'Russian Federation', phone: '7' },
  { code: 'RW', label: 'Rwanda', phone: '250' },
  { code: 'SA', label: 'Saudi Arabia', phone: '966' },
  { code: 'SB', label: 'Solomon Islands', phone: '677' },
  { code: 'SC', label: 'Seychelles', phone: '248' },
  { code: 'SD', label: 'Sudan', phone: '249' },
  { code: 'SE', label: 'Sweden', phone: '46' },
  { code: 'SG', label: 'Singapore', phone: '65' },
  { code: 'SH', label: 'Saint Helena', phone: '290' },
  { code: 'SI', label: 'Slovenia', phone: '386' },
  { code: 'SJ', label: 'Svalbard and Jan Mayen', phone: '47' },
  { code: 'SK', label: 'Slovakia', phone: '421' },
  { code: 'SL', label: 'Sierra Leone', phone: '232' },
  { code: 'SM', label: 'San Marino', phone: '378' },
  { code: 'SN', label: 'Senegal', phone: '221' },
  { code: 'SO', label: 'Somalia', phone: '252' },
  { code: 'SR', label: 'Suriname', phone: '597' },
  { code: 'SS', label: 'South Sudan', phone: '211' },
  { code: 'ST', label: 'Sao Tome and Principe', phone: '239' },
  { code: 'SV', label: 'El Salvador', phone: '503' },
  { code: 'SX', label: 'Sint Maarten (Dutch part)', phone: '1-721' },
  { code: 'SY', label: 'Syrian Arab Republic', phone: '963' },
  { code: 'SZ', label: 'Swaziland', phone: '268' },
  { code: 'TC', label: 'Turks and Caicos Islands', phone: '1-649' },
  { code: 'TD', label: 'Chad', phone: '235' },
  { code: 'TF', label: 'French Southern Territories', phone: '262' },
  { code: 'TG', label: 'Togo', phone: '228' },
  { code: 'TH', label: 'Thailand', phone: '66' },
  { code: 'TJ', label: 'Tajikistan', phone: '992' },
  { code: 'TK', label: 'Tokelau', phone: '690' },
  { code: 'TL', label: 'Timor-Leste', phone: '670' },
  { code: 'TM', label: 'Turkmenistan', phone: '993' },
  { code: 'TN', label: 'Tunisia', phone: '216' },
  { code: 'TO', label: 'Tonga', phone: '676' },
  { code: 'TR', label: 'Turkey', phone: '90' },
  { code: 'TT', label: 'Trinidad and Tobago', phone: '1-868' },
  { code: 'TV', label: 'Tuvalu', phone: '688' },
  { code: 'TW', label: 'Taiwan, Province of China', phone: '886' },
  { code: 'TZ', label: 'United Republic of Tanzania', phone: '255' },
  { code: 'UA', label: 'Ukraine', phone: '380' },
  { code: 'UG', label: 'Uganda', phone: '256' },
  { code: 'US', label: 'United States', phone: '1', suggested: true },
  { code: 'UY', label: 'Uruguay', phone: '598' },
  { code: 'UZ', label: 'Uzbekistan', phone: '998' },
  { code: 'VA', label: 'Holy See (Vatican City State)', phone: '379' },
  { code: 'VC', label: 'Saint Vincent and the Grenadines', phone: '1-784' },
  { code: 'VE', label: 'Venezuela', phone: '58' },
  { code: 'VG', label: 'British Virgin Islands', phone: '1-284' },
  { code: 'VI', label: 'US Virgin Islands', phone: '1-340' },
  { code: 'VN', label: 'Vietnam', phone: '84' },
  { code: 'VU', label: 'Vanuatu', phone: '678' },
  { code: 'WF', label: 'Wallis and Futuna', phone: '681' },
  { code: 'WS', label: 'Samoa', phone: '685' },
  { code: 'XK', label: 'Kosovo', phone: '383' },
  { code: 'YE', label: 'Yemen', phone: '967' },
  { code: 'YT', label: 'Mayotte', phone: '262' },
  { code: 'ZA', label: 'South Africa', phone: '27' },
  { code: 'ZM', label: 'Zambia', phone: '260' },
  { code: 'ZW', label: 'Zimbabwe', phone: '263' },
];

export const DEFAULT_PICTURE: string =
  "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/08ff2967557635.5b3dce5725b0d.jpg";
export const FLORIAN_PP: string =
  "https://scontent-cdg2-1.xx.fbcdn.net/v/t1.0-9/1010155_920552407957107_2288511525204403945_n.jpg?_nc_cat=111&ccb=2&_nc_sid=174925&_nc_ohc=orluLBUFka0AX-CE7oJ&_nc_ht=scontent-cdg2-1.xx&oh=604f1be7307070f0559229b33a29e57f&oe=5FE4B40D";

export const DELPHINE_PP: string =
  "https://scontent-cdt1-1.xx.fbcdn.net/v/t1.0-9/123346148_4026631660686124_8765939619000282630_o.jpg?_nc_cat=105&ccb=2&_nc_sid=09cbfe&_nc_ohc=VA2vt3VDJO8AX8HRARh&_nc_ht=scontent-cdt1-1.xx&oh=dc497c3d215cd29fd0579a7acc7e6c6d&oe=5FE6099E";

export const G_KEY: string = "AIzaSyBKiJklpTe2GKWKaWevMOMZQSQxmbnpQV0";

interface PositionInterface {
  lat: number;
  lng: number;
}

export interface PlaceInterface {
  user: UserInterface;
  name: string;
  country: string;
  preview: string;
  code: string;
  position: PositionInterface;
}

export interface UserInterface {
  firstName: string;
  lastName: string;
  profilePicture: string;
}

export const users: UserInterface[] = [
  {
    firstName: "Florian",
    lastName: "Sahbi",
    profilePicture: FLORIAN_PP,
  },
  {
    firstName: "Delphine",
    lastName: "Masson",
    profilePicture: DELPHINE_PP,
  },
]

export let places: PlaceInterface[] = [
  {
    user: users[1],
    code: "AT",
    position: {
      lat: 47.804057,
      lng: 13.045099,
    },
    name: "Salzbourg",
    country: "Autriche",
    preview: "https://www.alibabuy.com/photos/library/1500/12369.jpg",
  },
  {
    user: users[1],
    code: "CA",
    position: {
      lat: 53.287665,
      lng: -132.218761,
    },
    name: "Haida Gwaii",
    country: "Canada",
    preview:
      "https://www.steppestravel.com/app/uploads/2019/06/ocean-landscape-haida-gwaii-canada-1920x1080.jpg",
  },
  {
    user: users[1],
    code: "PT",
    position: {
      lat: 32.737901,
      lng: -17.211161,
    },
    name: "Jardim do Mar",
    country: "Portugal",
    preview:
      "https://photo.comptoir.fr/asset/guide/2634/621585-1260x630-jardim-do-mar-madere-portugal.jpg",
  },
  {
    user: users[1],
    code: "FR",
    position: {
      lat: 43.901095,
      lng: 5.295653,
    },
    name: "Le Sentier des Ocres",
    country: "France",
    preview:
      "https://www.luberon-apt.fr/sites/aptluberon/files/styles/ratio_8_3_xl/public/page/lesocresb8.jpg?itok=7eHiTExy",
  },
  {
    user: users[1],
    code: "CH",
    position: {
      lat: 47.152592,
      lng: 8.487855,
    },
    name: "Ägerisee Schifffahrt",
    country: "Suisse",
    preview: "https://static.stnet.ch/mice/images/42581-o.jpg",
  },
  {
    user: users[1],
    code: "FR",
    position: {
      lat: 43.077278,
      lng: 5.783200,
    },
    name: "Île des Embiez",
    country: "France",
    preview:
      "https://www.hyeres-tourisme.com/wp-content/uploads/2018/05/J-Veyssade-Hyeres-Tourisme-51_1024x650_hyeres_tourisme.jpg",
  },
  {
    user: users[1],
    code: "FR",
    position: {
      lat: 46.708817,
      lng: 5.647260,
    },
    name: "Les reculées du Jura",
    country: "France",
    preview:
      "https://planet-terre.ens-lyon.fr/planetterre/objets/Images/Img515/515-reculee-Jura-04.jpg",
  },
  {
    user: users[1],
    code: "ES",
    position: {
      lat: 43.447471,
      lng: -4.885959,
    },
    name: "Playa de Gulpiyuri",
    country: "Espagne",
    preview:
      "https://ucmedia.er2.co/es/cor/5/6/1600/o_1cl6kbu2o15uchld1h9b8k66m4u.jpg",
  },
  {
    user: users[0],
    code: "JP",
    position: {
      lat: 35.360612,
      lng: 138.727071,
    },
    name: "Mont Fuji",
    country: "Japon",
    preview:
      "https://blog.fitmyrun.fr/wp-content/uploads/2018/05/Mont-Fuji.jpg",
  },
  {
    user: users[0],
    code: "JP",
    position: {
      lat: 34.213042,
      lng: 135.591571,
    },
    name: "Mont Koya",
    country: "Japon",
    preview:
      "https://photo.comptoir.fr/asset/mot-cle/602/mont-koya-614887-1440x670.jpg",
  },
  {
    user: users[0],
    code: "JP",
    position: {
      lat: 36.559351,
      lng: 136.654128,
    },
    name: "Kanazawa",
    country: "Japon",
    preview: "https://pix6.agoda.net/geo/city/18826/1_18826_02.jpg?s=1920x822",
  },
  {
    user: users[0],
    code: "JP",
    position: {
      lat: 34.967216,
      lng: 135.772751,
    },
    name: "Fushimi Inari Taicha",
    country: "Japon",
    preview:
      "https://d1wv60jaas5mse.cloudfront.net/images/uploads/production/post_images/2d86bc2cb466ea_Famous%20Red%20Gates%20at%20Fushimi%20Inari%20Taisha.jpg",
  },
  {
    user: users[0],
    code: "AR",
    position: {
      lat: -49.320623,
      lng: -72.894869,
    },
    name: "Sendero al Fitz Roy",
    country: "Argentine",
    preview:
      "https://milesandlove.com/system/attachments/1644/xxlarge/impressionnant-fitz-roy.jpg?1509449940",
  },
  {
    user: users[0],
    code: "JP",
    position: {
      lat: 35.039270,
      lng: 135.728902,
    },
    name: "Kinkaku-Ji",
    country: "Japon",
    preview:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Water_reflection_of_Kinkaku-ji_Temple_a_sunny_day%2C_Kyoto%2C_Japan.jpg/1200px-Water_reflection_of_Kinkaku-ji_Temple_a_sunny_day%2C_Kyoto%2C_Japan.jpg",
  },
  {
    user: users[0],
    code: "JP",
    position: {
      lat: 35.714503,
      lng: 139.796530,
    },
    name: "Senso-Ji",
    country: "Japon",
    preview: "https://ak.picdn.net/shutterstock/videos/6325205/thumb/1.jpg",
  },
  {
    user: users[0],
    code: "JP",
    position: {
      lat: 35.610610,
      lng: 139.197221,
    },
    name: "Arashiyama",
    country: "Japon",
    preview:
      "https://www.jrailpass.com/blog/wp-content/uploads/2016/05/arashiyama-bamboo-grove-kyoto-e1466611768221-1280x720.jpg",
  },
  {
    user: users[0],
    code: "JP",
    position: {
      lat: 35.514604,
      lng: 138.750130,
    },
    name: "Lac Kawaguchi",
    country: "Japon",
    preview: "https://www.myatlas.xyz/gallery/2000/5a17eee8569619a891ej.jpg?1",
  },
  {
    user: users[0],
    code: "IT",
    position: {
      lat: 40.633232,
      lng: 14.602777,
    },
    name: "Costiera Amalfitana",
    country: "Italie",
    preview:
      "https://admin.pettinaviaggi.it/images/viaggi/1cc408ac-9e93-4178-87b8-8df339515633_AMALFI2.jpg",
  },
];